spring:
  application:


    name: mcp-spring-java
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: kycflow-sse-server
        version: 0.0.1
        type: SYNC
        stdio: false
        sse-message-endpoint: /mcp/message
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true


management:
  tracing:
    enabled: true

server:
  port: 8080

# application.yml
logging:
  level:
    # Core rerequest–response logging
    org.springframework.web: TRACE
    org.springframework.http: TRACE          # encoders / decoders
    org.springframework.web.servlet.mvc.method.annotation.SseEmitter: TRACE
    # Spring‑AI MCP internals
    org.springframework.ai.mcp: TRACE
    io.modelcontextprotocol: TRACE            # MCP protocol layer
    # Reactor Netty (if you use WebFlux)
    reactor.netty.http.server: DEBUG